[[redirects]]
  from = "/contatos/*"
  to = "/contatos/index.html"
  status = 200

[[redirects]]
  from = "/portfolio/*"
  to = "/portfolio/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
